import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst } from 'workbox-strategies';
import * as workbox from 'workbox-build';


declare const self: ServiceWorkerGlobalScope;

// Precache all the assets generated by your build process
precacheAndRoute(self.__WB_MANIFEST);

// Add your custom caching strategies here

// Cache API responses using the Stale-While-Revalidate strategy
registerRoute(
  // Match any requests that match this pattern (change it to match your API endpoints)
  ({ url }) => url.pathname.startsWith('/'),
  new StaleWhileRevalidate({
    cacheName: 'api-cache',
    plugins: [
      // Optionally, you can add expiration for cached responses
      new workbox.expiration.ExpirationPlugin({
        maxEntries: 100, // Adjust the maximum number of cached responses
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache specific routes with custom strategies
registerRoute(
  ({ url }) => {
    // Customize this condition to match the routes you want to cache differently
    return url.pathname.endsWith('.jpg') || url.pathname.endsWith('.png');
  },
  new StaleWhileRevalidate({
    cacheName: 'image-cache',
    plugins: [
      new workbox.expiration.ExpirationPlugin({
        maxEntries: 50, // Adjust the maximum number of cached images
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 Days
      }),
    ],
  })
);

// Cache navigation requests with the NetworkFirst strategy
registerRoute(
  new NavigationRoute(
    createHandlerBoundToURL('/index.html')
  )
);

// For other requests, use a NetworkFirst strategy
registerRoute(
  ({ url }) => {
    // Customize this condition to match other routes if needed
    return true;
  },
  new NetworkFirst({
    cacheName: 'default-cache', // Adjust the cache name
  })
);
