import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute, NavigationRoute } from 'workbox-routing';
import { StaleWhileRevalidate } from 'workbox-strategies';

// 👇 Add these imports if not already present
import { ExpirationPlugin } from 'workbox-expiration';

declare const self: ServiceWorkerGlobalScope;

// ✅ Place these listeners here
self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Precache all the assets generated by your build process
precacheAndRoute(self.__WB_MANIFEST);

// Cache all HTTP requests, including images, using the Stale-While-Revalidate strategy
registerRoute(
  ({ request }) =>
    request.mode === 'navigate' ||
    (request.method === 'GET' && request.destination === 'document') ||
    request.destination === 'image',
  new StaleWhileRevalidate({
    cacheName: 'http-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Cache specific image files with a custom strategy
registerRoute(
  ({ url }) => url.pathname.endsWith('.jpg') || url.pathname.endsWith('.png'),
  new StaleWhileRevalidate({
    cacheName: 'image-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 7 * 24 * 60 * 60, // 7 Days
      }),
    ],
  })
);

// Cache navigation requests (e.g., index.html)
registerRoute(
  new NavigationRoute(
    createHandlerBoundToURL(`${self.location.origin}/index.html`)
  )
);
