import React, { useState, useEffect } from "react";
import { Button, Form, Input, InputNumber, Select, Modal, message } from "antd";

interface AddEditVariantModalProps {
  open: boolean;
  onClose: () => void;
  onSubmit: (variantData: any) => void;
  editingVariant?: any;
  productName?: string;
}

const AddEditVariantModal: React.FC<AddEditVariantModalProps> = ({
  open,
  onClose,
  onSubmit,
  editingVariant,
  productName = "PRODUCT"
}) => {
  console.log('AddEditVariantModal rendered with props:', { open, editingVariant, productName });
  const [form] = Form.useForm();
  const [variantData, setVariantData] = useState({
    name: '',
    attributeType: '',
    attributeValue: '',
    quantity: 0,
    sku: '',
    price: 0,
    vat_type: 'STANDARD',
    timestamp: Date.now()
  });

  useEffect(() => {
    if (open) {
      if (editingVariant) {
        // Edit mode - populate form with existing variant data
        form.setFieldsValue({
          name: editingVariant.name,
          attributeType: editingVariant.attributeType,
          attributeValue: editingVariant.attributeValue,
          quantity: editingVariant.quantity,
          price: editingVariant.price,
          vat_type: editingVariant.vat_type
        });
        setVariantData({
          name: editingVariant.name,
          attributeType: editingVariant.attributeType,
          attributeValue: editingVariant.attributeValue,
          quantity: editingVariant.quantity,
          sku: editingVariant.sku,
          price: editingVariant.price,
          vat_type: editingVariant.vat_type,
          timestamp: Date.now()
        });
      } else {
        // Add mode - reset form
        form.resetFields();
        form.setFieldsValue({
          vat_type: 'STANDARD'
        });
        setVariantData({
          name: '',
          attributeType: '',
          attributeValue: '',
          quantity: 0,
          sku: '',
          price: 0,
          vat_type: 'STANDARD',
          timestamp: Date.now()
        });
      }
    }
  }, [open, editingVariant, form]);

  const generateSku = (name: string) => {
    return `${productName.toUpperCase()}-${name?.toUpperCase() || 'VAR'}-${(variantData.timestamp % 10000).toString().padStart(4, '0')}`;
  };

  const handleSubmit = async () => {
    try {
      const values = await form.validateFields();
      const autoGeneratedSku = generateSku(values.name);
      
      const finalVariantData = {
        ...values,
        sku: autoGeneratedSku,
        id: editingVariant?.id || Date.now().toString(),
        attributes: {
          [values.attributeType]: values.attributeValue
        }
      };

      onSubmit(finalVariantData);
      onClose();
      message.success(`Variant ${editingVariant ? 'updated' : 'added'} successfully`);
    } catch (error) {
      console.error('Form validation error:', error);
    }
  };

  const handleCancel = () => {
    onClose();
  };

  return (
    <Modal
      title={editingVariant ? 'Edit Variant' : 'Add New Variant'}
      open={open}
      onCancel={handleCancel}
      footer={[
        <Button key="cancel" onClick={handleCancel}>
          Cancel
        </Button>,
        <Button key="submit" type="primary" onClick={handleSubmit}>
          {editingVariant ? 'Update Variant' : 'Add Variant'}
        </Button>
      ]}
      width={600}
      destroyOnClose
      zIndex={9999}
      maskStyle={{ backgroundColor: 'rgba(0,0,0,0.8)' }}
    >
      <Form
        form={form}
        layout="vertical"
        onFinish={handleSubmit}
      >
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '16px' }}>
          <Form.Item
            name="name"
            label="Variant Name"
            rules={[{ required: true, message: "Variant name is required" }]}
          >
            <Input
              placeholder="e.g., Red, Small"
              onChange={(e) => {
                const newName = e.target.value;
                setVariantData(prev => ({ ...prev, name: newName }));
              }}
            />
          </Form.Item>

          <Form.Item label="SKU">
            <Input
              placeholder="Auto-generated"
              value={generateSku(variantData.name)}
              disabled
              style={{ backgroundColor: '#f5f5f5' }}
            />
          </Form.Item>

          <Form.Item
            name="attributeType"
            label="Variant Type"
            rules={[{ required: true, message: "Variant type is required" }]}
          >
            <Select
              placeholder="Select type"
              onChange={(value) => {
                setVariantData(prev => ({ ...prev, attributeType: value }));
              }}
            >
              <Select.Option value="color">Color</Select.Option>
              <Select.Option value="size">Size</Select.Option>
              <Select.Option value="material">Material</Select.Option>
              <Select.Option value="other">Other</Select.Option>
            </Select>
          </Form.Item>

          <Form.Item
            name="attributeValue"
            label="Variant Value"
            rules={[{ required: true, message: "Variant value is required" }]}
          >
            <Input
              placeholder="e.g., Red, M, Cotton"
              onChange={(e) => {
                setVariantData(prev => ({ ...prev, attributeValue: e.target.value }));
              }}
            />
          </Form.Item>

          <Form.Item
            name="quantity"
            label="Quantity"
            rules={[{ required: true, message: "Quantity is required" }]}
          >
            <InputNumber
              placeholder="0"
              min={0}
              style={{ width: '100%' }}
              onChange={(value) => {
                setVariantData(prev => ({ ...prev, quantity: value || 0 }));
              }}
            />
          </Form.Item>

          <Form.Item
            name="price"
            label="Price (Ksh)"
            rules={[{ required: true, message: "Price is required" }]}
          >
            <InputNumber
              placeholder="0.00"
              min={0}
              precision={2}
              style={{ width: '100%' }}
              addonBefore="Ksh."
              onChange={(value) => {
                setVariantData(prev => ({ ...prev, price: value || 0 }));
              }}
            />
          </Form.Item>
        </div>

        </Form>
    </Modal>
  );
};

export default AddEditVariantModal;
